/* The following code was generated by JFlex 1.4.3 on 11/12/13 03:36 */

package br.poli.ecomp.nemesis.avaliador;
import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 11/12/13 03:36 from the specification file
 * <tt>main/jflex/avaliador/ALexico.jflex</tt>
 */
public class ALexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\51\1\50\1\0\2\51\22\0\1\51\1\0\1\46\1\0"+
    "\1\1\6\0\1\36\1\37\1\0\1\43\1\0\12\42\6\0\1\44"+
    "\1\34\1\45\1\31\2\45\1\35\12\45\1\32\1\45\1\30\7\45"+
    "\1\0\1\47\4\0\1\10\1\17\1\23\1\11\1\5\1\2\1\15"+
    "\1\7\1\13\1\26\1\45\1\20\1\24\1\14\1\3\1\25\1\45"+
    "\1\6\1\12\1\4\1\22\1\16\1\33\1\27\1\21\1\45\1\40"+
    "\1\0\1\41\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\2\0\1\6"+
    "\20\0\1\7\1\10\27\0\1\5\1\7\36\0\1\11"+
    "\1\12\6\0\1\13\3\0\1\14\10\0\1\15\6\0"+
    "\1\16\3\0\1\17\4\0\1\20\1\0\1\21\1\0"+
    "\1\22\1\23\1\24\5\0\1\25\3\0\1\26\4\0"+
    "\1\27\10\0\1\30\7\0\1\31\1\32\3\0\1\33"+
    "\2\0\1\34\10\0\1\35\16\0\1\36\1\0\1\37"+
    "\4\0\1\40";

  private static int [] zzUnpackAction() {
    int [] result = new int[198];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\124\0\124\0\124\0\176\0\250"+
    "\0\322\0\124\0\374\0\u0126\0\u0150\0\u017a\0\u01a4\0\u01ce"+
    "\0\u01f8\0\u0222\0\u024c\0\u0276\0\u02a0\0\u02ca\0\u02f4\0\u031e"+
    "\0\u0348\0\u0372\0\u039c\0\124\0\u03c6\0\u03f0\0\u041a\0\u0444"+
    "\0\u046e\0\u0498\0\u04c2\0\u04ec\0\u0516\0\u0540\0\u056a\0\u0594"+
    "\0\u05be\0\u05e8\0\u0612\0\u063c\0\u0666\0\u0690\0\u06ba\0\u06e4"+
    "\0\u070e\0\u0738\0\u0762\0\u0372\0\u078c\0\u07b6\0\u07e0\0\u080a"+
    "\0\u0834\0\u085e\0\u0888\0\u08b2\0\u08dc\0\u0906\0\u0930\0\u095a"+
    "\0\u0984\0\u09ae\0\u09d8\0\u0a02\0\u0a2c\0\u0a56\0\u0a80\0\u0aaa"+
    "\0\u0ad4\0\u0afe\0\u0b28\0\u0b52\0\u0b7c\0\u0ba6\0\u0bd0\0\u0bfa"+
    "\0\u0c24\0\u0c4e\0\u0c78\0\124\0\124\0\u0ca2\0\u0ccc\0\u0cf6"+
    "\0\u0d20\0\u0d4a\0\u0d74\0\124\0\u0d9e\0\u0dc8\0\u0df2\0\124"+
    "\0\u0e1c\0\u0e46\0\u0e70\0\u0e9a\0\u0ec4\0\u0eee\0\u0f18\0\u0f42"+
    "\0\124\0\u0f6c\0\u0f96\0\u0fc0\0\u0fea\0\u1014\0\u103e\0\124"+
    "\0\u1068\0\u1092\0\u10bc\0\124\0\u10e6\0\u1110\0\u113a\0\u1164"+
    "\0\124\0\u118e\0\124\0\u11b8\0\124\0\124\0\124\0\u11e2"+
    "\0\u120c\0\u1236\0\u1260\0\u128a\0\124\0\u12b4\0\u12de\0\u1308"+
    "\0\124\0\u1332\0\u135c\0\u1386\0\u13b0\0\124\0\u13da\0\u1404"+
    "\0\u142e\0\u1458\0\u1482\0\u14ac\0\u14d6\0\u1500\0\124\0\u152a"+
    "\0\u1554\0\u157e\0\u15a8\0\u15d2\0\u15fc\0\u1626\0\124\0\124"+
    "\0\u1650\0\u167a\0\u16a4\0\124\0\u16ce\0\u16f8\0\124\0\u1722"+
    "\0\u174c\0\u1776\0\u17a0\0\u17ca\0\u17f4\0\u181e\0\u1848\0\124"+
    "\0\u1872\0\u189c\0\u18c6\0\u18f0\0\u191a\0\u1944\0\u196e\0\u1998"+
    "\0\u19c2\0\u19ec\0\u1a16\0\u1a40\0\u1a6a\0\u1a94\0\124\0\u1abe"+
    "\0\124\0\u1ae8\0\u1b12\0\u1b3c\0\u1b66\0\124";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[198];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\2\34\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\0\1\10\1\0\1\11\1\0\2\12\2\0\1\13"+
    "\1\14\1\15\2\0\1\16\1\17\1\20\1\21\2\0"+
    "\1\22\1\23\1\24\2\0\1\25\1\26\1\27\1\30"+
    "\5\0\1\31\132\0\1\7\1\32\10\0\34\33\7\0"+
    "\1\33\4\0\46\11\1\34\1\35\2\11\3\0\1\36"+
    "\2\0\1\37\70\0\1\40\32\0\1\41\4\0\1\42"+
    "\43\0\1\43\60\0\1\44\45\0\1\45\44\0\1\46"+
    "\1\47\1\50\14\0\1\51\35\0\1\52\53\0\1\53"+
    "\44\0\1\54\62\0\1\55\40\0\1\56\4\0\1\57"+
    "\51\0\1\60\11\0\1\61\35\0\1\62\50\0\1\63"+
    "\106\0\1\64\11\0\34\33\4\0\1\65\2\0\1\33"+
    "\4\0\50\11\1\0\1\11\3\0\1\66\53\0\1\67"+
    "\50\0\1\70\67\0\1\71\33\0\1\72\55\0\1\73"+
    "\53\0\1\74\43\0\1\75\65\0\1\76\41\0\1\77"+
    "\45\0\1\100\64\0\1\101\35\0\1\102\54\0\1\103"+
    "\54\0\1\104\53\0\1\105\60\0\1\106\53\0\1\107"+
    "\31\0\1\110\22\0\1\111\42\0\1\112\34\0\1\113"+
    "\61\0\1\114\100\0\1\65\13\0\1\115\52\0\1\116"+
    "\57\0\1\117\43\0\1\120\64\0\1\121\42\0\1\122"+
    "\73\0\1\123\23\0\1\124\2\0\1\125\57\0\1\126"+
    "\37\0\1\127\51\0\1\130\73\0\1\131\45\0\1\132"+
    "\42\0\1\133\57\0\1\134\46\0\1\135\41\0\1\136"+
    "\70\0\1\137\33\0\1\140\55\0\1\141\42\0\1\142"+
    "\47\0\1\143\64\0\1\144\41\0\1\145\100\0\1\146"+
    "\20\0\1\147\103\0\1\150\21\0\1\151\51\0\1\152"+
    "\51\0\1\153\51\0\1\154\51\0\1\155\57\0\1\156"+
    "\43\0\1\157\71\0\1\160\34\0\1\161\46\0\1\162"+
    "\56\0\1\163\52\0\1\164\62\0\1\165\40\0\1\166"+
    "\43\0\1\167\53\0\1\170\50\0\1\171\57\0\1\172"+
    "\51\0\1\173\45\0\1\174\47\0\1\175\51\0\1\176"+
    "\51\0\1\177\67\0\1\200\41\0\1\201\60\0\1\202"+
    "\45\0\1\203\40\0\1\204\50\0\1\205\66\0\1\206"+
    "\54\0\1\207\36\0\1\210\43\0\1\211\57\0\1\212"+
    "\57\0\1\213\36\0\1\214\61\0\1\215\40\0\1\216"+
    "\65\0\1\217\43\0\1\220\63\0\1\221\45\0\1\222"+
    "\43\0\1\223\72\0\1\224\30\0\1\225\53\0\1\226"+
    "\47\0\1\227\44\0\1\230\57\0\1\231\66\0\1\232"+
    "\26\0\1\233\47\0\1\234\53\0\1\235\51\0\1\236"+
    "\50\0\1\237\57\0\1\240\43\0\1\241\70\0\1\242"+
    "\57\0\1\243\26\0\1\244\51\0\1\245\75\0\1\246"+
    "\40\0\1\247\33\0\1\250\55\0\1\251\74\0\1\252"+
    "\41\0\1\253\35\0\1\254\46\0\1\255\70\0\1\256"+
    "\34\0\1\257\51\0\1\260\57\0\1\261\43\0\1\262"+
    "\56\0\1\263\62\0\1\264\40\0\1\265\43\0\1\266"+
    "\52\0\1\267\50\0\1\270\60\0\1\271\70\0\1\272"+
    "\32\0\1\273\41\0\1\274\70\0\1\275\32\0\1\276"+
    "\62\0\1\277\42\0\1\300\60\0\1\301\47\0\1\302"+
    "\43\0\1\303\60\0\1\304\41\0\1\305\62\0\1\306"+
    "\35\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7056];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\4\11\1\1\2\0\1\11\20\0\1\1\1\11"+
    "\27\0\2\1\36\0\2\11\6\0\1\11\3\0\1\11"+
    "\10\0\1\11\6\0\1\11\3\0\1\11\4\0\1\11"+
    "\1\0\1\11\1\0\3\11\5\0\1\11\3\0\1\11"+
    "\4\0\1\11\10\0\1\11\7\0\2\11\3\0\1\11"+
    "\2\0\1\11\10\0\1\11\16\0\1\11\1\0\1\11"+
    "\4\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[198];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ALexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public ALexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 126) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 20: 
          { return new Symbol(sym.SOLVER);
          }
        case 33: break;
        case 14: 
          { return new Symbol(sym.GROUP);
          }
        case 34: break;
        case 31: 
          { return new Symbol(sym.FREEANSWERQUESTION);
          }
        case 35: break;
        case 22: 
          { return new Symbol(sym.WEIGHT);
          }
        case 36: break;
        case 23: 
          { return new Symbol(sym.SUBJECT);
          }
        case 37: break;
        case 21: 
          { return new Symbol(sym.COURSE);
          }
        case 38: break;
        case 19: 
          { return new Symbol(sym.ANSWER);
          }
        case 39: break;
        case 3: 
          { return new Symbol(sym.OPENBRACKET);
          }
        case 40: break;
        case 28: 
          { return new Symbol(sym.UNIVERSITY);
          }
        case 41: break;
        case 26: 
          { return new Symbol(sym.VARIABLES);
          }
        case 42: break;
        case 4: 
          { return new Symbol(sym.CLOSEBRACKET);
          }
        case 43: break;
        case 5: 
          { return new Symbol(sym.NUMBER, new Float(yytext()));
          }
        case 44: break;
        case 27: 
          { return new Symbol(sym.PROFESSOR);
          }
        case 45: break;
        case 13: 
          { return new Symbol(sym.TITLE);
          }
        case 46: break;
        case 29: 
          { return new Symbol(sym.MAXIMUMSCORE);
          }
        case 47: break;
        case 15: 
          { return new Symbol(sym.CAMPI);
          }
        case 48: break;
        case 32: 
          { return new Symbol(sym.MULTIPLECHOICEQUESTION);
          }
        case 49: break;
        case 10: 
          { return new Symbol(sym.DATA);
          }
        case 50: break;
        case 12: 
          { return new Symbol(sym.MATH);
          }
        case 51: break;
        case 30: 
          { return new Symbol(sym.TRUEFALSEQUESTION);
          }
        case 52: break;
        case 24: 
          { return new Symbol(sym.SETTINGS);
          }
        case 53: break;
        case 1: 
          { return new Symbol(sym.SUM);
          }
        case 54: break;
        case 18: 
          { return new Symbol(sym.HEADER);
          }
        case 55: break;
        case 7: 
          { return new Symbol(sym.VARIABLE);
          }
        case 56: break;
        case 16: 
          { return new Symbol(sym.FOOTER);
          }
        case 57: break;
        case 8: 
          { return new Symbol(sym.STRING, yytext());
          }
        case 58: break;
        case 9: 
          { return new Symbol(sym.DATE);
          }
        case 59: break;
        case 6: 
          { /* ignora espaços e saltos de linha */
          }
        case 60: break;
        case 17: 
          { return new Symbol(sym.OPTION);
          }
        case 61: break;
        case 11: 
          { return new Symbol(sym.BODY);
          }
        case 62: break;
        case 25: 
          { return new Symbol(sym.STATEMENT);
          }
        case 63: break;
        case 2: 
          { return new Symbol(sym.SEP);
          }
        case 64: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {     return new Symbol(sym.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
