
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Dec 11 03:49:34 GMT-03:00 2013
//----------------------------------------------------

package br.poli.ecomp.nemesis.avaliador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPTION = 16;
  public static final int TRUEFALSEQUESTION = 22;
  public static final int COURSE = 8;
  public static final int SUM = 29;
  public static final int DATE = 11;
  public static final int PROFESSOR = 12;
  public static final int DATA = 20;
  public static final int CAMPI = 7;
  public static final int VARIABLE = 31;
  public static final int FREEANSWERQUESTION = 19;
  public static final int SOLVER = 21;
  public static final int MATH = 27;
  public static final int STRING = 32;
  public static final int VARIABLES = 4;
  public static final int MULTIPLECHOICEQUESTION = 14;
  public static final int UNIVERSITY = 6;
  public static final int NUMBER = 30;
  public static final int EOF = 0;
  public static final int TITLE = 10;
  public static final int FOOTER = 24;
  public static final int ANSWER = 17;
  public static final int SEP = 28;
  public static final int error = 1;
  public static final int CLOSEBRACKET = 26;
  public static final int OPENBRACKET = 25;
  public static final int BODY = 5;
  public static final int HEADER = 2;
  public static final int STATEMENT = 23;
  public static final int SUBJECT = 9;
  public static final int SETTINGS = 3;
  public static final int MAXIMUMSCORE = 13;
  public static final int GROUP = 15;
  public static final int WEIGHT = 18;
}

