
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 24 14:00:12 BRT 2013
//----------------------------------------------------

package avaliador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 12;
  public static final int DIVI = 6;
  public static final int A = 7;
  public static final int COS = 10;
  public static final int EOF = 0;
  public static final int VAR = 11;
  public static final int PROD = 5;
  public static final int SEN = 9;
  public static final int error = 1;
  public static final int DIFE = 4;
  public static final int ELEV = 2;
  public static final int SOMA = 3;
  public static final int F = 8;
}

