/*
 * Generated by classgen, version 1.3
 * 11/12/13 02:54
 */
package br.poli.ecomp.nemesis.syntaxtree;

public abstract class BCom implements SyntaxNode {

  private SyntaxNode parent;

  public Title getTitle() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setTitle(Title title) {
    throw new ClassCastException("tried to call abstract method");
  }

  public LQuestion getLquestion() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setLquestion(LQuestion lquestion) {
    throw new ClassCastException("tried to call abstract method");
  }

  public Weight getWeight() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setWeight(Weight weight) {
    throw new ClassCastException("tried to call abstract method");
  }

  public SyntaxNode getParent() {
    return parent;
  }

  public void setParent(SyntaxNode parent) {
    this.parent = parent;
  }

  public abstract void accept(Visitor visitor);
  public abstract void childrenAccept(Visitor visitor);
  public abstract void traverseTopDown(Visitor visitor);
  public abstract void traverseBottomUp(Visitor visitor);
  public String toString() {
    return toString("");
  }

  public abstract String toString(String tab);
}
