/*
 * Generated by classgen, version 1.3
 * 11/12/13 03:00
 */
package br.poli.ecomp.nemesis.syntaxtree;

public class Body implements SyntaxNode {

  private SyntaxNode parent;
  private LBCom lbcom;

  public Body (LBCom lbcom) {
    this.lbcom = lbcom;
    if (lbcom != null) lbcom.setParent(this);
  }

  public LBCom getLbcom() {
    return lbcom;
  }

  public void setLbcom(LBCom lbcom) {
    this.lbcom = lbcom;
  }

  public SyntaxNode getParent() {
    return parent;
  }

  public void setParent(SyntaxNode parent) {
    this.parent = parent;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (lbcom != null) lbcom.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (lbcom != null) lbcom.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (lbcom != null) lbcom.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString() {
    return toString("");
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("Body(\n");
      if (lbcom != null)
        buffer.append(lbcom.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [Body]");
    return buffer.toString();
  }
}
