/*
 * Generated by classgen, version 1.3
 * 11/12/13 01:07
 */
package br.poli.ecomp.nemesis.syntaxtree;

public class LBCom implements SyntaxNode {

  private SyntaxNode parent;
  private BCom bcom;
  private LBCom prox;

  public LBCom (BCom bcom, LBCom prox) {
    this.bcom = bcom;
    if (bcom != null) bcom.setParent(this);
    this.prox = prox;
    if (prox != null) prox.setParent(this);
  }

  public BCom getBcom() {
    return bcom;
  }

  public void setBcom(BCom bcom) {
    this.bcom = bcom;
  }

  public LBCom getProx() {
    return prox;
  }

  public void setProx(LBCom prox) {
    this.prox = prox;
  }

  public SyntaxNode getParent() {
    return parent;
  }

  public void setParent(SyntaxNode parent) {
    this.parent = parent;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (bcom != null) bcom.accept(visitor);
    if (prox != null) prox.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (bcom != null) bcom.traverseTopDown(visitor);
    if (prox != null) prox.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (bcom != null) bcom.traverseBottomUp(visitor);
    if (prox != null) prox.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString() {
    return toString("");
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("LBCom(\n");
      if (bcom != null)
        buffer.append(bcom.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (prox != null)
        buffer.append(prox.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [LBCom]");
    return buffer.toString();
  }
}
