/*
 * Generated by classgen, version 1.3
 * 11/12/13 01:07
 */
package br.poli.ecomp.nemesis.syntaxtree;

public class LHCom implements SyntaxNode {

  private SyntaxNode parent;
  private HCom hcom;
  private LHCom prox;

  public LHCom (HCom hcom, LHCom prox) {
    this.hcom = hcom;
    if (hcom != null) hcom.setParent(this);
    this.prox = prox;
    if (prox != null) prox.setParent(this);
  }

  public HCom getHcom() {
    return hcom;
  }

  public void setHcom(HCom hcom) {
    this.hcom = hcom;
  }

  public LHCom getProx() {
    return prox;
  }

  public void setProx(LHCom prox) {
    this.prox = prox;
  }

  public SyntaxNode getParent() {
    return parent;
  }

  public void setParent(SyntaxNode parent) {
    this.parent = parent;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (hcom != null) hcom.accept(visitor);
    if (prox != null) prox.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (hcom != null) hcom.traverseTopDown(visitor);
    if (prox != null) prox.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (hcom != null) hcom.traverseBottomUp(visitor);
    if (prox != null) prox.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString() {
    return toString("");
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("LHCom(\n");
      if (hcom != null)
        buffer.append(hcom.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (prox != null)
        buffer.append(prox.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [LHCom]");
    return buffer.toString();
  }
}
