/*
 * Generated by classgen, version 1.3
 * 11/12/13 01:07
 */
package br.poli.ecomp.nemesis.syntaxtree;

public class LNum implements SyntaxNode {

  private SyntaxNode parent;
  private float num;
  private LNum prox;

  public LNum (float num, LNum prox) {
    this.num = num;
    this.prox = prox;
    if (prox != null) prox.setParent(this);
  }

  public float getNum() {
    return num;
  }

  public void setNum(float num) {
    this.num = num;
  }

  public LNum getProx() {
    return prox;
  }

  public void setProx(LNum prox) {
    this.prox = prox;
  }

  public SyntaxNode getParent() {
    return parent;
  }

  public void setParent(SyntaxNode parent) {
    this.parent = parent;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (prox != null) prox.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (prox != null) prox.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (prox != null) prox.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString() {
    return toString("");
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("LNum(\n");
    buffer.append("  "+tab+num);
    buffer.append("\n");
      if (prox != null)
        buffer.append(prox.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [LNum]");
    return buffer.toString();
  }
}
