/*
 * Generated by classgen, version 1.3
 * 11/12/13 01:07
 */
package br.poli.ecomp.nemesis.syntaxtree;

public class LSCom implements SyntaxNode {

  private SyntaxNode parent;
  private SCom scom;
  private LSCom prox;

  public LSCom (SCom scom, LSCom prox) {
    this.scom = scom;
    if (scom != null) scom.setParent(this);
    this.prox = prox;
    if (prox != null) prox.setParent(this);
  }

  public SCom getScom() {
    return scom;
  }

  public void setScom(SCom scom) {
    this.scom = scom;
  }

  public LSCom getProx() {
    return prox;
  }

  public void setProx(LSCom prox) {
    this.prox = prox;
  }

  public SyntaxNode getParent() {
    return parent;
  }

  public void setParent(SyntaxNode parent) {
    this.parent = parent;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (scom != null) scom.accept(visitor);
    if (prox != null) prox.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (scom != null) scom.traverseTopDown(visitor);
    if (prox != null) prox.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (scom != null) scom.traverseBottomUp(visitor);
    if (prox != null) prox.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString() {
    return toString("");
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("LSCom(\n");
      if (scom != null)
        buffer.append(scom.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (prox != null)
        buffer.append(prox.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [LSCom]");
    return buffer.toString();
  }
}
