/*
 * Generated by classgen, version 1.3
 * 11/12/13 02:54
 */
package br.poli.ecomp.nemesis.syntaxtree;

public class Option implements SyntaxNode {

  private SyntaxNode parent;
  private LContent content;

  public Option (LContent content) {
    this.content = content;
    if (content != null) content.setParent(this);
  }

  public LContent getContent() {
    return content;
  }

  public void setContent(LContent content) {
    this.content = content;
  }

  public SyntaxNode getParent() {
    return parent;
  }

  public void setParent(SyntaxNode parent) {
    this.parent = parent;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (content != null) content.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (content != null) content.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (content != null) content.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString() {
    return toString("");
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("Option(\n");
      if (content != null)
        buffer.append(content.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [Option]");
    return buffer.toString();
  }
}
