/*
 * Generated by classgen, version 1.3
 * 11/12/13 03:36
 */
package br.poli.ecomp.nemesis.syntaxtree;

public class Title extends HCom {

  private LContent content;

  public Title (LContent content) {
    this.content = content;
    if (content != null) content.setParent(this);
  }

  public LContent getContent() {
    return content;
  }

  public void setContent(LContent content) {
    this.content = content;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (content != null) content.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (content != null) content.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (content != null) content.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("Title(\n");
      if (content != null)
        buffer.append(content.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [Title]");
    return buffer.toString();
  }
}
