/*
 * Generated by classgen, version 1.3
 * 24/10/13 14:00
 */
package avaliador.syntaxtree;

public class Cos extends Expr {

  private Expr a;

  public Cos (Expr a) {
    this.a = a;
    if (a != null) a.setParent(this);
  }

  public Expr getA() {
    return a;
  }

  public void setA(Expr a) {
    this.a = a;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (a != null) a.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (a != null) a.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (a != null) a.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("Cos(\n");
      if (a != null)
        buffer.append(a.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [Cos]");
    return buffer.toString();
  }
}
