/*
 * Generated by classgen, version 1.3
 * 24/10/13 14:00
 */
package avaliador.syntaxtree;

public abstract class VisitorAdaptor implements Visitor {

  public void visit(Expr expr) { visit(); }
  public void visit(Numero numero) { visit(); }
  public void visit(Soma soma) { visit(); }
  public void visit(Subtracao subtracao) { visit(); }
  public void visit(Multiplicacao multiplicacao) { visit(); }
  public void visit(Divisao divisao) { visit(); }
  public void visit(Potencia potencia) { visit(); }
  public void visit(Seno seno) { visit(); }
  public void visit(Cos cos) { visit(); }
  public void visit(Variavel variavel) { visit(); }

  public void visit() { }

}
