/*
 * Generated by classgen, version 1.3
 * 11/12/13 01:44
 */

package br.poli.ecomp.nemesis.syntaxtree;

public interface SyntaxNode {

  public void accept(Visitor visitor);

  public void childrenAccept(Visitor visitor);
  public void traverseBottomUp(Visitor visitor);
  public void traverseTopDown(Visitor visitor);

  public SyntaxNode getParent();
  public void setParent(SyntaxNode parent);
}
