/*
 * Generated by classgen, version 1.3
 * 27/11/13 14:42
 */
package imperative_lang.syntaxtree;

public abstract class Expr implements SyntaxNode {

  private SyntaxNode parent;

  public int getVal() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setVal(int val) {
    throw new ClassCastException("tried to call abstract method");
  }

  public Expr getA() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setA(Expr a) {
    throw new ClassCastException("tried to call abstract method");
  }

  public String getOp() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setOp(String op) {
    throw new ClassCastException("tried to call abstract method");
  }

  public Expr getB() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setB(Expr b) {
    throw new ClassCastException("tried to call abstract method");
  }

  public String getNome() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setNome(String nome) {
    throw new ClassCastException("tried to call abstract method");
  }

  public Expr getArray() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setArray(Expr array) {
    throw new ClassCastException("tried to call abstract method");
  }

  public Expr getIndex() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setIndex(Expr index) {
    throw new ClassCastException("tried to call abstract method");
  }

  public Expr getStruct() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setStruct(Expr struct) {
    throw new ClassCastException("tried to call abstract method");
  }

  public String getFieldName() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setFieldName(String fieldName) {
    throw new ClassCastException("tried to call abstract method");
  }

  public Expr getPointer() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setPointer(Expr pointer) {
    throw new ClassCastException("tried to call abstract method");
  }

  public Expr getVariable() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setVariable(Expr variable) {
    throw new ClassCastException("tried to call abstract method");
  }

  public SyntaxNode getParent() {
    return parent;
  }

  public void setParent(SyntaxNode parent) {
    this.parent = parent;
  }

  public abstract void accept(Visitor visitor);
  public abstract void childrenAccept(Visitor visitor);
  public abstract void traverseTopDown(Visitor visitor);
  public abstract void traverseBottomUp(Visitor visitor);
  public String toString() {
    return toString("");
  }

  public abstract String toString(String tab);
}
