/*
 * Generated by classgen, version 1.3
 * 27/11/13 14:42
 */
package imperative_lang.syntaxtree;

public class TStruct extends Type {

  private Fields fields;

  public TStruct (Fields fields) {
    this.fields = fields;
    if (fields != null) fields.setParent(this);
  }

  public Fields getFields() {
    return fields;
  }

  public void setFields(Fields fields) {
    this.fields = fields;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (fields != null) fields.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (fields != null) fields.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (fields != null) fields.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("TStruct(\n");
      if (fields != null)
        buffer.append(fields.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [TStruct]");
    return buffer.toString();
  }
}
