
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 27 14:42:23 BRT 2013
//----------------------------------------------------

package imperative_lang;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ELSE = 18;
  public static final int STRUCT = 21;
  public static final int INT = 19;
  public static final int THEN = 17;
  public static final int PONTO = 23;
  public static final int WHILE = 16;
  public static final int A_COLCH = 13;
  public static final int F_P = 8;
  public static final int IF = 15;
  public static final int F_CHAVE = 12;
  public static final int PV = 10;
  public static final int NUM = 24;
  public static final int EOF = 0;
  public static final int A_P = 7;
  public static final int A_CHAVE = 11;
  public static final int error = 1;
  public static final int POINTER = 22;
  public static final int EQ = 9;
  public static final int BOOL = 20;
  public static final int OP4 = 6;
  public static final int OP3 = 5;
  public static final int OP2 = 4;
  public static final int OP1 = 3;
  public static final int VAR = 2;
  public static final int F_COLCH = 14;
}

